name: pynta_env
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - spglib
  - networkx
  - ase >=3.22.1
  - scipy
  - numpy
  - pyyaml
  - sella
  - sphinx
  - glpk==5.0
  - fireworks
  - jax <=0.2.28
  - cp2k==7.1
